name: Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths:
      - '**'
  pull_request:
    branches: [ main ]
    paths:
      - '**'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - dev-prod

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.platform }} (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            platform: linux
            arch: x64
            
          # Windows
          - os: windows-latest
            platform: win
            arch: x64
            
          # macOS Universal (Intel + Apple Silicon)
          - os: macos-latest
            platform: mac
            arch: universal
            
          # macOS Intel only
          - os: macos-13
            platform: mac
            arch: x64
            
          # macOS Apple Silicon only  
          - os: macos-latest
            platform: mac
            arch: arm64

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Setup directory structure
        run: mkdir -p datalayer

      - name: Checkout desktop repository
        uses: actions/checkout@v4
        with:
          path: datalayer/desktop
          fetch-depth: 0

      - name: Checkout core repository
        uses: actions/checkout@v4
        with:
          repository: goanpeca/core
          ref: enh/sdk-updates
          path: datalayer/core

      - name: Debug directory structure
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== Directory structure ==="
          find datalayer -type d -maxdepth 3
          echo "=== Core lib contents ==="
          ls -la datalayer/core/lib/ || echo "No core lib found"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Skip core repository postinstall scripts
        working-directory: datalayer/core
        run: |
          if [ -f package.json ]; then
            echo "Removing problematic scripts from core package.json"
            cp package.json package.json.backup
            node -e "const pkg = require('./package.json'); delete pkg.scripts?.postinstall; delete pkg.scripts?.prepare; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
          fi
        shell: bash

      - name: Install core repository dependencies and build
        working-directory: datalayer/core
        run: |
          echo "Installing core dependencies..."
          npm install --ignore-scripts
          echo "Building core SDK lib..."
          npm run build:lib
          echo "Building core full with increased memory..."
          export NODE_OPTIONS="--max-old-space-size=8192"
          npm run build
        shell: bash

      - name: Install desktop dependencies
        working-directory: datalayer/desktop
        run: npm install

      # Linux Build
      - name: Build for Linux
        if: matrix.platform == 'linux'
        working-directory: datalayer/desktop
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "dev-prod" ]; then
            npm run dist:dev-prod:linux
          else
            npm run dist:linux
          fi
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux artifacts
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: datalayer-desktop-linux-${{ matrix.arch }}
          path: |
            datalayer/desktop/dist-electron/*.AppImage
            datalayer/desktop/dist-electron/*.deb
            datalayer/desktop/dist-electron/*.rpm
            datalayer/desktop/dist-electron/*.snap
          retention-days: 30

      # Windows Build
      - name: Build for Windows
        if: matrix.platform == 'win'
        working-directory: datalayer/desktop
        shell: bash
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "dev-prod" ]; then
            npm run dist:dev-prod:win
          else
            npm run dist:win
          fi
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        if: matrix.platform == 'win'
        uses: actions/upload-artifact@v4
        with:
          name: datalayer-desktop-win-${{ matrix.arch }}
          path: |
            datalayer/desktop/dist-electron/*.exe
            datalayer/desktop/dist-electron/*.msi
          retention-days: 30

      # macOS Build
      - name: Build for macOS
        if: matrix.platform == 'mac'
        working-directory: datalayer/desktop
        run: |
          # Skip code signing if certificates aren't available
          if [ -z "${{ secrets.MACOS_CERTIFICATE }}" ]; then
            echo "No code signing certificates available, building unsigned app"
            export CSC_IDENTITY_AUTO_DISCOVERY=false
          fi

          # Build based on architecture and build type
          if [ "${{ matrix.arch }}" = "universal" ]; then
            if [ "${{ github.event.inputs.build_type }}" = "dev-prod" ]; then
              npm run dist:dev-prod:mac
            else
              npm run dist:mac-universal
            fi
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            npm run dist:mac-arm
          else
            npm run dist:mac-intel
          fi
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload macOS artifacts
        if: matrix.platform == 'mac'
        uses: actions/upload-artifact@v4
        with:
          name: datalayer-desktop-mac-${{ matrix.arch }}
          path: |
            datalayer/desktop/dist-electron/*.dmg
            datalayer/desktop/dist-electron/*.zip
            datalayer/desktop/dist-electron/*.pkg
          retention-days: 30

      # Upload build logs on failure
      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            datalayer/desktop/npm-debug.log
            datalayer/desktop/dist-electron/builder-debug.yml
            datalayer/desktop/dist-electron/builder-effective-config.yaml
          retention-days: 7

  test-artifacts:
    name: Test Artifacts
    needs: build
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts structure
        run: |
          echo "Artifact Structure:"
          find artifacts -type f -name "*.AppImage" -o -name "*.exe" -o -name "*.dmg" -o -name "*.deb" -o -name "*.rpm" | head -20

      - name: Check artifact sizes
        run: |
          echo "Artifact Sizes:"
          find artifacts -type f \( -name "*.AppImage" -o -name "*.exe" -o -name "*.dmg" -o -name "*.deb" -o -name "*.rpm" \) -exec ls -lh {} \;
