name: Code Quality

on:
  push:
    branches: [ main ]
    paths:
      - '**'
  pull_request:
    branches: [ main ]
    paths:
      - '**'
  workflow_dispatch:

concurrency:
  group: code-quality-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup directory structure
        run: mkdir -p datalayer

      - name: Checkout desktop repository
        uses: actions/checkout@v4
        with:
          path: datalayer/desktop
          fetch-depth: 0
          retries: 3

      - name: Checkout core repository
        uses: actions/checkout@v4
        with:
          repository: goanpeca/core
          ref: enh/sdk-updates
          path: datalayer/core
          retries: 3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Skip core repository postinstall scripts
        working-directory: datalayer/core
        run: |
          if [ -f package.json ]; then
            echo "Removing problematic scripts from core package.json"
            cp package.json package.json.backup
            node -e "const pkg = require('./package.json'); delete pkg.scripts?.postinstall; delete pkg.scripts?.prepare; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
          fi
        shell: bash

      - name: Install core repository dependencies and build
        working-directory: datalayer/core
        run: |
          echo "Installing core dependencies..."
          npm install --ignore-scripts
          echo "Building core SDK lib..."
          npm run build:lib
          echo "Building core full with increased memory..."
          export NODE_OPTIONS="--max-old-space-size=8192"
          npm run build
        shell: bash

      - name: Install desktop dependencies
        working-directory: datalayer/desktop
        run: npm install

      - name: Check code formatting
        working-directory: datalayer/desktop
        run: |
          echo "Checking code formatting..."
          npm run format:check

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup directory structure
        run: mkdir -p datalayer

      - name: Checkout desktop repository
        uses: actions/checkout@v4
        with:
          path: datalayer/desktop
          fetch-depth: 0
          retries: 3

      - name: Checkout core repository
        uses: actions/checkout@v4
        with:
          repository: goanpeca/core
          ref: enh/sdk-updates
          path: datalayer/core
          retries: 3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Skip core repository postinstall scripts
        working-directory: datalayer/core
        run: |
          if [ -f package.json ]; then
            echo "Removing problematic scripts from core package.json"
            cp package.json package.json.backup
            node -e "const pkg = require('./package.json'); delete pkg.scripts?.postinstall; delete pkg.scripts?.prepare; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
          fi
        shell: bash

      - name: Install core repository dependencies and build
        working-directory: datalayer/core
        run: |
          echo "Installing core dependencies..."
          npm install --ignore-scripts
          echo "Building core SDK lib..."
          npm run build:lib
          echo "Building core full with increased memory..."
          export NODE_OPTIONS="--max-old-space-size=8192"
          npm run build
        shell: bash

      - name: Install desktop dependencies
        working-directory: datalayer/desktop
        run: npm install

      - name: Run ESLint
        working-directory: datalayer/desktop
        run: |
          echo "Running ESLint..."
          npm run lint -- --max-warnings 0

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup directory structure
        run: mkdir -p datalayer

      - name: Checkout desktop repository
        uses: actions/checkout@v4
        with:
          path: datalayer/desktop
          fetch-depth: 0
          retries: 3

      - name: Checkout core repository
        uses: actions/checkout@v4
        with:
          repository: goanpeca/core
          ref: enh/sdk-updates
          path: datalayer/core
          retries: 3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Skip core repository postinstall scripts
        working-directory: datalayer/core
        run: |
          if [ -f package.json ]; then
            echo "Removing problematic scripts from core package.json"
            cp package.json package.json.backup
            node -e "const pkg = require('./package.json'); delete pkg.scripts?.postinstall; delete pkg.scripts?.prepare; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
          fi
        shell: bash

      - name: Install core repository dependencies and build
        working-directory: datalayer/core
        run: |
          echo "Installing core dependencies..."
          npm install --ignore-scripts
          echo "Building core SDK lib..."
          npm run build:lib
          echo "Building core full with increased memory..."
          export NODE_OPTIONS="--max-old-space-size=8192"
          npm run build
        shell: bash

      - name: Install desktop dependencies
        working-directory: datalayer/desktop
        run: npm install

      - name: Run TypeScript type checking
        working-directory: datalayer/desktop
        run: |
          echo "Running TypeScript type checking..."
          npm run type-check
