name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'typedoc.json'
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

concurrency:
  group: docs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup directory structure
        run: mkdir -p datalayer

      - name: Checkout desktop repository
        uses: actions/checkout@v4
        with:
          path: datalayer/desktop
          fetch-depth: 0

      - name: Checkout core repository
        uses: actions/checkout@v4
        with:
          repository: goanpeca/core
          ref: sdk/core-updates
          path: datalayer/core

      - name: Setup build environment
        uses: ./datalayer/desktop/.github/actions/setup-environment
        with:
          skip-debug: "true"

      - name: Generate TypeDoc documentation
        working-directory: datalayer/desktop
        run: |
          echo "Generating TypeDoc documentation..."
          npm run docs

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: datalayer/desktop/docs/
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./datalayer/desktop/docs
          cname: datalayer-desktop.netlify.app