name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**'
  pull_request:
    branches: [ main ]
    paths:
      - '**'
  workflow_dispatch:

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup directory structure
        run: mkdir -p datalayer

      - name: Checkout desktop repository
        uses: actions/checkout@v4
        with:
          path: datalayer/desktop
          fetch-depth: 0

      - name: Checkout core repository
        uses: actions/checkout@v4
        with:
          repository: goanpeca/core
          ref: sdk/core-updates
          path: datalayer/core

      - name: Setup build environment
        uses: ./datalayer/desktop/.github/actions/setup-environment
        with:
          skip-debug: "true"

      - name: Run unit tests
        working-directory: datalayer/desktop
        run: |
          echo "Running unit tests..."
          npm run test:unit
